### ISSUE TITLE
Backend system refused server

### ISSUE THREAD

**Issue by ger-pakon** [BeamMP/BeamMP-Server#14]
@lionkor with commit e4979bb6e2dfe05741163b24ff08c2f4ee3098db and later, I'm not able to connect to the master server.

Is there a change in your infrastructure planned?

Cheers,
Pakon

**Comment by lionkor** [comment]
Hello, please only use tagged versions when building from source. Newest master branch commits are to be considered broken until tagged.

We're working on a new release and some (major) infrastructure changes, which is why master might currently be in a slightly broken state. 

So for now use the latest tag.

**Comment by lionkor** [comment]
@Starystars67 im correct in assuming that, right now, this is expected behavior?

To be clear, this is referring to the commit that introduces the new backend

**Comment by ger-pakon** [comment]
@lionkor sounds great, I'm excited in what will change. :) Ist there any official roadmap? You can Close this requests.

**Comment by lionkor** [comment]
We have a trello: https://trello.com/b/Kw75j3zZ/beamngdrive-multiplayer
