### ISSUE TITLE
[Bug] TNetwork::OpenID may assign the same ID to two players

### ISSUE THREAD

**Issue by lionkor** [BeamMP/BeamMP-Server#154]
If two players both call TNetwork::OpenID at the same time, the function may assign them both the same ID. This can be fixed by making the calls exclusive to each other in some way.

**Comment by OfficialLambdax** [comment]
so two players ended up logged in with the same ID? what happend if one then disconnected? or when both have spawned car?
Maybe related to https://github.com/BeamMP/BeamMP-Server/issues/119

**Comment by lionkor** [comment]
It may be related, yeah. I just saw the code allows this *technically*. It's a SUPER unlikely data race, but since it can happen, it'll be fixed in v3.2.0. The most common possible cause for #119 is also fixed in v3.2.0 (a packet impersonation bug).

**Comment by OfficialLambdax** [comment]
For me both bugs actually make up #119. Because anyone could broadcast packets for any vehicle. And since there where then two players with the same id, that could explain the rapid teleportation of one car between two moving spots and the difference in the json formats of the PosRot (Zp) packets <- which previously indicated that the packets come from two different origins
