### ISSUE TITLE
[Bug] Running `settings help` returns nothing

### ISSUE THREAD

**Issue by Mack29446** [BeamMP/BeamMP-Server#158]
**Fill out general information**
OS: Linux
BeamMP-Server Version: 3.1.1

**Describe the bug**
Running the `settings help` command, as suggested within the `help` command, returns nothing

**To Reproduce**
1. Run `settings help`
2. Observe nothing happen

**Expected behavior**
Something to happen

**Comment by lionkor** [comment]
Yeah, I'm an idiot and forgot to remove `settings` from 3.1.x. It'll be implemented properly in 3.2.0, and has `get`, `set`, etc.

Please feel free to try it (contact me to get a pre-release-build for example), or see an example here:
![image](https://user-images.githubusercontent.com/29932116/203498960-767835d4-a1c0-4f0d-b418-f9e3656ad348.png)

So this will be fixed by v3.2.0, and can't be fixed in v3.1.1 (as it doesn't exist).

**Comment by jimkoen** [comment]
Should this maybe go alongside refactoring settings all together? The behavior from the screenshot is proving hard to implement without some ugly code like a massive if/else if/else if etc  statement.

If so, I would go ahead and open a separate issue for that.

**Comment by lionkor** [comment]
Feel free to refactor the settings, but be aware they are used quite literally everywhere. Of course some settings shouldn't be accessible, only AuthKey comes to mind.

The TOML has to stay etc. and the behavior from the users side should be very similar. Make a new issue for sure!
