### ISSUE TITLE
Report more information when requesting /pkToUser

### ISSUE THREAD

**Issue by Mack29446** [BeamMP/BeamMP-Server#303]
Please could the server report the following to the pkToUser endpoint, along with the user's PK:
* Server AuthKey
* IP of user attempting to join

These can be added to the json with any name

**Comment by sla-ppy** [comment]
@lionkor Assign me this issue, please.

**Comment by sla-ppy** [comment]
Line 292 in TNetwork.cpp:
![kép](https://github.com/BeamMP/BeamMP-Server/assets/55049912/6c066142-9a53-4463-a75e-d4b2c8cff3cb)

So I believe I found the way to return the authkey which was simple enough.
Problem arose when I wanted to figure out how Client->GetIdentifiers() returns data.

It returns an unordered map with two std::strings in it, but I am not sure what type of structure it would have.
How can I go about testing this? I need to connect to my local server as a client and check it out that way dont I?

Also since we cant return a full map of strings, and instead we only want to return the actual IP address of the client, how do I guarantee that this is what I am returning from the map and not some random garbage?

Why does the user have multiple identifiers to begin with?
