### ISSUE TITLE
[Bug] 2.4.0: BeamMP ID not available at the time of onPlayerAuth

### ISSUE THREAD

**Issue by 20dka** [BeamMP/BeamMP-Server#56]
This makes banning a player based on their forum account not "properly" possible. The options are to ban based on username, or to kick them after they pass onPlayerAuth. The issue with the latter is the kick message doesn't get passed through to the joining client, they just get stuck loading

**Comment by lionkor** [comment]
In #50 we're adding an `ip` field to the `MP.GetPlayerIdentifiers()` table, which exists on auth. The forum ID should obviously also be available, I agree.

**Comment by Starystars67** [comment]
@20dka I have just tried this and you can call the `GetPlayerIdentifiers()` function inside of the onPlayerConnecting and it does seem to work. I have just experimented with this in finishing up the new control scripts for the official servers.

**Comment by lionkor** [comment]
@Starystars67 Yes, but you can't cancel onPlayerConnecting or onPlayerJoining. This means that banning, like @20dka said, isn't possible like this. We *could* try to make those cancelable, but that makes little sense conceptually ("auth" is where you are let in).

**Comment by Starystars67** [comment]
@lionkor yeah, on auth is not the way to do it. It would be better done within on player connecting I feel. Thoughts?
This way we could add either a return or just call DropPlayer which is what I am doing now. The issue is that it results in a code 2 rather than the reason that I provide to DropPlayer.

**Comment by lionkor** [comment]
Auth is where the player is "let in", so that's the *correct* place to cancel ("you cant come in because you're banned").

If I understand @20dka's request correctly, we should pass the player ID to onPlayerAuth, so that the auth can be cancelled by forum id, ip address, or name, not just name. This makes banning people by ip or forum id possible.

**Comment by Starystars67** [comment]
Fair enough, In that case I just am using a work around based on my past experience of how it worked on other games. 
My running theory was that `onAuth` would be to handle just that and `onPlayerConnecting` would be where you stop them connecting?
